-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Documents table
CREATE TABLE IF NOT EXISTS documents (
    id VARCHAR(255) PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    source TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Chunks table with vector embeddings
CREATE TABLE IF NOT EXISTS chunks (
    id VARCHAR(255) PRIMARY KEY,
    document_id VARCHAR(255) NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    position INTEGER NOT NULL,
    embedding vector(768) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create index for vector similarity search using IVFFlat
-- Note: This requires at least 1000 rows for optimal performance
-- For dev/testing with fewer rows, we use a simple index
CREATE INDEX IF NOT EXISTS chunks_embedding_idx ON chunks
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Create index on document_id for faster joins
CREATE INDEX IF NOT EXISTS chunks_document_id_idx ON chunks(document_id);

-- Insert sample document for testing
INSERT INTO documents (id, title, content, source, created_at)
VALUES (
    'doc-sample-1',
    'Introduction to Artificial Intelligence',
    'Artificial Intelligence (AI) is the simulation of human intelligence by machines. It includes machine learning, natural language processing, and computer vision.',
    'sample-docs/ai-intro.txt',
    CURRENT_TIMESTAMP
) ON CONFLICT (id) DO NOTHING;

-- Insert sample chunks with embeddings (using random vectors for demo)
-- In production, these would be generated by the embedding service
INSERT INTO chunks (id, document_id, text, position, embedding, created_at)
VALUES (
    'chunk-sample-1',
    'doc-sample-1',
    'Artificial Intelligence (AI) is the simulation of human intelligence by machines.',
    0,
    array_fill(0.1::float, ARRAY[768])::vector,
    CURRENT_TIMESTAMP
) ON CONFLICT (id) DO NOTHING;

INSERT INTO chunks (id, document_id, text, position, embedding, created_at)
VALUES (
    'chunk-sample-2',
    'doc-sample-1',
    'Machine learning is a subset of AI that enables systems to learn from data.',
    1,
    array_fill(0.2::float, ARRAY[768])::vector,
    CURRENT_TIMESTAMP
) ON CONFLICT (id) DO NOTHING;
