package com.ai.common.domain;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;
import java.util.Objects;

/**
 * Represents an answer generated by the LLM.
 */
public final class Answer {
    private final String text;
    private final List<Citation> citations;
    private final String modelUsed;

    @JsonCreator
    public Answer(
            @JsonProperty("text") String text,
            @JsonProperty("citations") List<Citation> citations,
            @JsonProperty("modelUsed") String modelUsed) {
        if (text == null || text.isBlank()) {
            throw new IllegalArgumentException("Answer text cannot be null or blank");
        }
        if (citations == null) {
            throw new IllegalArgumentException("Citations cannot be null");
        }
        if (modelUsed == null || modelUsed.isBlank()) {
            throw new IllegalArgumentException("Model used cannot be null or blank");
        }
        this.text = text;
        this.citations = List.copyOf(citations);
        this.modelUsed = modelUsed;
    }

    @JsonGetter("text")
    public String text() {
        return text;
    }

    @JsonGetter("citations")
    public List<Citation> citations() {
        return citations;
    }

    @JsonGetter("modelUsed")
    public String modelUsed() {
        return modelUsed;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!(obj instanceof Answer other)) return false;
        return Objects.equals(text, other.text) &&
               Objects.equals(citations, other.citations) &&
               Objects.equals(modelUsed, other.modelUsed);
    }

    @Override
    public int hashCode() {
        return Objects.hash(text, citations, modelUsed);
    }

    @Override
    public String toString() {
        return "Answer[text=" + text +
               ", citationCount=" + citations.size() +
               ", modelUsed=" + modelUsed + "]";
    }
}
